# Generated by Django 5.2.3 on 2025-11-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('airport_city', models.CharField(max_length=50)),
                ('airport_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlightService',
            fields=[
                ('service_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TravelClass',
            fields=[
                ('travel_class_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('flight_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departure_date_time', models.DateTimeField()),
                ('arrival_date_time', models.DateTimeField()),
                ('airplane_type', models.CharField(max_length=50)),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='main.airport')),
                ('source_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='main.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_of_reservation', models.DateField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_status_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('payment_due_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='main.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='SeatDetails',
            fields=[
                ('seat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.flightdetails')),
                ('travel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.travelclass')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.seatdetails'),
        ),
        migrations.CreateModel(
            name='FlightCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from_date', models.DateField()),
                ('valid_to_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_costs', to='main.seatdetails')),
            ],
            options={
                'unique_together': {('seat', 'valid_from_date')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='main.flightservice')),
                ('travel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='main.travelclass')),
            ],
            options={
                'unique_together': {('travel_class', 'service')},
            },
        ),
    ]
