# Generated by Django 5.2.3 on 2025-11-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatdetails',
            name='seat_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
