# Generated by Django 5.2.3 on 2025-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_seatdetails_seat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='flight_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flightservice',
            name='service_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='payment_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travelclass',
            name='travel_class_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
